name: Vale readability checks
description: Analyze all documentation files for readability metrics
on:
  workflow_dispatch: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  vale-readability:
    runs-on: ubuntu-latest
    container:
      image: jdkato/vale
      volumes:
      - ${{ github.workspace }}
    steps:
    - uses: actions/checkout@v4
    - name: Synchronize Vale modules
      run: vale sync --config=.vale/readability.ini
    - name: Calculate readability metrics
      run: find docs -name \*.md | xargs vale --config=.vale/readability.ini
